import type {Metadata} from 'next'
import {Geist, Geist_Mono} from 'next/font/google'
import NavBar from '@/components/NavBar'
import './globals.css'
import {AuthProvider} from '@/components/AuthContext'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Client component to handle the body
function ClientBody({ children }: { children: React.ReactNode }) {
  return (
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-white text-gray-800`}>
      <AuthProvider>
        <NavBar />
        {children}
      </AuthProvider>
    </body>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ClientBody>{children}</ClientBody>
    </html>
  )
}